server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
  
spring:
  application:
    name: API-GATEWAY 
  security:
    user:
     name: admin
     password: admin  
  cloud:
    gateway:
      routes:
        - id : DEPT-SERVICE
          uri: lb://DEPT-SERVICE
          predicates:
            - Path=/dept/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack
        - id: EMP-SERVICE
          uri: lb://EMP-SERVICE
          predicates: 
            - Path=/emp/**
          filters:
            - name: CircuitBreaker
              args:
                 name: DEPT-SERVICE
                 fallbackuri: forward:/empServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


